# datasource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/provider_service?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    appname: provider-service
    instance-id: provider-service
    prefer-ip-address: true
    ip-address: 127.0.0.1